POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "username": "shubha123",
  "password": "password",
  "email": "shubha@example.com",
  "name": "Shubham Jakate"
}


###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
  "email":"shubha@example.com",
  "password":"password"

}